# TODO: this doesn't work because github-hosted windows machines are just crap in terms
# of speed, and there's too many timing-dependent tests.
name: Post New Release

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Release Title'
        required: true
        type: string
      body:
        description: 'Release Body'
        required: true
        type: string
        default: "As usual, you do not need to download this if you already have a working install - use the auto-updater instead."
      tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  make-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Set git to use LF instead of CRLF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
        with:
          ref: stable
      - name: Set up JDK 17
        uses: oracle-actions/setup-java@v1.3.1
        with:
          release: '17'

      - name: Build with Maven
        #run: JAVA_HOME=$JAVA_HOME_17_X64 mvn -T3 clean install
        # TODO: make sure this runs with the correct java
        run: mvn -T1 clean install -Dsurefire.threadcount=1

      - name: Copy artifacts
        run: mv launcher/target/*.zip ./

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.title }}
          body: ${{ inputs.body }}
          tag_name: ${{ inputs.tag }}
          draft: true
          target_commitish: stable
          files: |
            triggevent-linux.zip
            triggevent-win-byoj.zip
            triggevent-win.zip

