# Grab cactbot timelines, make a pull request automatically

name: Extract Timelines

on:
  workflow_dispatch:
  schedule:
    - cron: '06 */6 * * *'


jobs:
  timelines:
    runs-on: self-hosted
    permissions:
      all: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn test -Pmaketimelines

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          commit-message: 'Automatic timeline update'
          branch: timeline-auto-update
          title: 'Automatic Timeline Update'
          body: 'Automatic extraction of Cactbot timelines'
          delete-branch: true